<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>Tinvo</RootNamespace>
		<ApplicationIcon>icon.ico</ApplicationIcon>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="icon.ico" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="icon.ico" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Serilog.Sinks.Debug" Version="3.0.0" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebView" Version="9.0.*" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Tinvo.Provider.MCP\Tinvo.Provider.MCP.csproj" />
		<ProjectReference Include="..\Tinvo\Tinvo.csproj" />
		<ProjectReference Include="..\Tinvo.Provider.Baidu\Tinvo.Provider.Baidu.csproj" />
		<ProjectReference Include="..\Tinvo.Provider.Ollama\Tinvo.Provider.Ollama.csproj" />
		<ProjectReference Include="..\Tinvo.Provider.OpenAI\Tinvo.Provider.OpenAI.csproj" />
		<ProjectReference Include="..\Tinvo.Provider.XunFei\Tinvo.Provider.XunFei.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="runtimes\linux-arm64\native\miniblink.so">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="runtimes\linux-x64\native\miniblink.so">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="runtimes\win-x64\native\miniblink.dll">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="runtimes\win-x86\native\miniblink.dll">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

	<PropertyGroup>
		<ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
	</PropertyGroup>
	
</Project>
